name: Deploy Server

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      # ghcrにログイン
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # イメージをビルド
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/server/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/server:latest
